### ISSUE TITLE
Memory leak in the `sendto` function

### ISSUE THREAD

**Issue by vgrocha** [janestreet/async_udp#1]
Hi there!

We are using the UDP module in the [ocaml-statsd-library](https://github.com/arenadotio/ocaml-statsd-client/blob/master/statsd-client-async/statsd_client_async.ml#L36) and it seems that there's a memory leak in the `sendto` function. 

This was reproduced in both `OCaml=v4.06.0+spacetime` + `async=v0.11`, and `OCaml=v4.08.0+spacetime` + `async=v0.13`. Here's the trimmed down version of the issue:

```
open Core
open Async

module Udp = Async_udp

let () = Shutdown.set_default_force (fun () -> after (sec 30.))

let n_packets = 100000
let socket_fd = Socket.fd (Socket.create (Socket.Type.udp))
let inet_addr = Caml.Unix.inet_addr_of_string "127.0.0.1"
let socket_address = Socket.Address.Inet.create inet_addr ~port:8125
let buf = "memleak" |> Iobuf.of_string |> Iobuf.read_only

let run_sendto () =
  let send = Udp.sendto () |> Or_error.ok_exn in
  Deferred.for_ 1 ~to_:n_packets ~do_:
    (fun i ->
       send socket_fd buf socket_address >>| fun () -> 
       if (i % 10000) = 0 then Gc.compact ();
       if (i = n_packets) then Shutdown.shutdown 0;
       Iobuf.reset buf)
  
let () =
  run_sendto () |> Deferred.don't_wait_for;
  never_returns (Scheduler.go ())
```

And the spacetime graph (12s of execution) and [its processed results](https://github.com/janestreet/async_udp/files/4403105/spacetime-31423.zip):

![image](https://user-images.githubusercontent.com/1419824/77918083-a2aa9c00-7258-11ea-9a64-82eef9d94d97.png)

**Comment by snowleopard** [comment]
I believe this issue has been resolved as described [here](https://github.com/janestreet/async_extra/issues/15#issuecomment-686614235). If that's not the case, please reopen.
